// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdjTcGiKFf-B5pyn2DcPQTrZGqimkfn2g',
    appId: '1:993433552292:web:4d304b6032ce9be11ced31',
    messagingSenderId: '993433552292',
    projectId: 'braketpay-mobile-app',
    authDomain: 'braketpay-mobile-app.firebaseapp.com',
    storageBucket: 'braketpay-mobile-app.appspot.com',
    measurementId: 'G-48F1VYKHEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqlhvk2KzXB3W5p8rEr8XY-N25RuyOxRs',
    appId: '1:993433552292:android:90f525092f88fcd41ced31',
    messagingSenderId: '993433552292',
    projectId: 'braketpay-mobile-app',
    storageBucket: 'braketpay-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuY1TEf_BHCs1Q2k4eRUgbwHynxmj2VhY',
    appId: '1:993433552292:ios:ae7ca495844755e81ced31',
    messagingSenderId: '993433552292',
    projectId: 'braketpay-mobile-app',
    storageBucket: 'braketpay-mobile-app.appspot.com',
    iosClientId: '993433552292-k5lqirrs07lduhtu2tmmfad8u1qs7cfq.apps.googleusercontent.com',
    iosBundleId: 'com.example.braketpay',
  );
}
