// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfFAn46NsSysS1WNDGei-cbrw645_uBGY',
    appId: '1:878106186057:web:74848c79b20af72bbeca98',
    messagingSenderId: '878106186057',
    projectId: 'braketpay-2cb32',
    authDomain: 'braketpay-2cb32.firebaseapp.com',
    storageBucket: 'braketpay-2cb32.appspot.com',
    measurementId: 'G-JC609DF1BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZv8pL1F-rAsZ9uZ7lhn6JmV1YHGar7Pw',
    appId: '1:878106186057:android:4f0aabc527195b4dbeca98',
    messagingSenderId: '878106186057',
    projectId: 'braketpay-2cb32',
    storageBucket: 'braketpay-2cb32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7eu3UOR8XAgtt9K9JzFVJhnNeyI5e7OI',
    appId: '1:878106186057:ios:f8f2189a15b07c63beca98',
    messagingSenderId: '878106186057',
    projectId: 'braketpay-2cb32',
    storageBucket: 'braketpay-2cb32.appspot.com',
    iosClientId: '878106186057-dr3m1nv2knbigpt9evf1ul1glvmo73hs.apps.googleusercontent.com',
    iosBundleId: 'com.example.braketpay',
  );
}
